### ISSUE TITLE
Building build-tor.sh with tor version 0.2.7.6 resulting in openssl linkable errors

### ISSUE THREAD

**Issue by ali-ht10** [mtigas/iOS-OnionBrowser#68]
Hi,

I'm trying to build the 3 script files,**build-libssl.sh, build-libevent.sh and build-tor.sh**. libssl and libevent builds successfully. But when I build tor.sh, everytime it fails with this:
checking for openssl directory... configure: WARNING: Could not find a linkable openssl.  If you have it installed somewhere unusual, you can specify an explicit path using --with-openssl-dir.

I'm running this on Xcode 7.3 and OSX10.11 el capitan.
I have autoconf 2.69 installed along with automake 1.15.
I know there is a patch which if applied to configure.ac, fixes this issue. I have applied that patch but the issue remains the same.

This is my patch file:
https://gist.github.com/ali-ht10/6d7232cf63e9394997c9ba6a12be8479

And I apply this patch file by using this command in build-tor.sh file, patch -p3 < ../../../build-patches/patch.diff

This is my config.log of tor:
https://gist.github.com/ali-ht10/5053c8f132caf1217cc671092050a75a

Please help. Thanks

**Comment by mtigas** [comment]
The 0.2.7.6 patch you have puts a fix in `configure.ac` (which is used to generate the `configure` script), but the Onion Browser build script uses an already-built `configure` file which comes with Tor.

In your edited version of `build-tor.sh` can you run `autoconf` after where you perform your patch, like
```
patch -p3 < ../../../build-patches/patch.diff
autoconf
```

You will need to have autoconf installed. (If you are using homebrew, you can do `brew install autoconf`.)

This seems to fix the issue in my own testing. Let me know if that works for you.

(Note that you only need to do this if you are using 0.2.7.6 — in the master branch, the build scripts are set up to use Tor 0.2.8.2-alpha, which already includes the patch.)

**Comment by ali-ht10** [comment]
Running autoconf did the trick.

I have a project in which I have to use the libraries generated from the build scripts. I added them into the project but now when I compiled it, there were alot of errors. E.g: 
Undefined symbols for architecture x86_64:
  "_auth1_encode", referenced from:
      _connection_or_compute_authenticate_cell_body in libtor.a(connection_or.o)
  "_auth1_free", referenced from:
      _connection_or_compute_authenticate_cell_body in libtor.a(connection_or.o)

see here:
https://gist.github.com/ali-ht10/b0522819029530c68b215496084daa39

My question is whether **ibed25519_ref10.a libed25519_donna.a libor-trunnel.a libkeccak-tiny.a** is a requirement for **tor 0.2.7.6**? I haven't included them in the build-tor.sh file. I'm just curious to know.

Thanks.

**Comment by mtigas** [comment]
Tor builds several helper libraries as part of Tor. The exact libraries depend on the version of Tor you want to build.

You can discover these yourself by commenting out `make clean`  in the middle of the build script, and the `rm` lines toward the end. The build script will probably crash fail after the first platform (since we don't clear the existing files), but you'll be able to see what is available in `build/src/tor-0.2.7.6`: the built libraries will be all files that end in `.a` in that directory and subdirectories.

If you want a simple answer, you can see the `build-tor.sh` here which contains the right libraries for Tor 0.2.7.x: https://github.com/mtigas/iOS-OnionBrowser/blob/v1.5.15/build-tor.sh I don't know what your version of the script is doing, but you will need to copy all of the libraries for when building each platform (line 247-254), you need to copy the headers (256-265), and combine the various platform versions  into a "universal" form that can run on all necessary devices (274-297).
